/* This file is auto-generated by scripts/generate-embedded-migrations.ts. */

import journalPath from "./migrations/meta/_journal.json" with { type: "file" };
import m_0000_initial from "./migrations/0000_initial.sql" with { type: "file" };
import m_0001_tricky_vance_astro from "./migrations/0001_tricky_vance_astro.sql" with { type: "file" };
import m_0002_lucky_psynapse from "./migrations/0002_lucky_psynapse.sql" with { type: "file" };
import m_0003_abnormal_harpoon from "./migrations/0003_abnormal_harpoon.sql" with { type: "file" };

export const embeddedMigrations = {
  journalPath,
  files: {
    "0000_initial": m_0000_initial,
    "0001_tricky_vance_astro": m_0001_tricky_vance_astro,
    "0002_lucky_psynapse": m_0002_lucky_psynapse,
    "0003_abnormal_harpoon": m_0003_abnormal_harpoon,
  },
} as const;
