import { join } from "node:path";

const rootDir = join(import.meta.dir, "..");
const migrationsDir = join(rootDir, "src", "db", "migrations");
const journalPath = join(migrationsDir, "meta", "_journal.json");
const outputPath = join(rootDir, "src", "db", "embedded-migrations.ts");

type Journal = {
  entries: Array<{
    tag: string;
  }>;
};

const journal = (await Bun.file(journalPath).json()) as Journal;
const tags = journal.entries.map((entry) => entry.tag);

const imports: string[] = [
  'import journalPath from "./migrations/meta/_journal.json" with { type: "file" };',
];
const fileMappings: string[] = [];

for (const tag of tags) {
  const varName = `m_${tag.replace(/[^a-zA-Z0-9]/g, "_")}`;
  imports.push(
    `import ${varName} from "./migrations/${tag}.sql" with { type: "file" };`,
  );
  fileMappings.push(`    "${tag}": ${varName},`);
}

const contents = [
  "/* This file is auto-generated by scripts/generate-embedded-migrations.ts. */",
  "",
  ...imports,
  "",
  "export const embeddedMigrations = {",
  "  journalPath,",
  "  files: {",
  ...fileMappings,
  "  },",
  "} as const;",
  "",
].join("\n");

await Bun.write(outputPath, contents);
console.log(`Generated ${outputPath}`);
